export const dashboardRoutes = {
  operations: "/dashboard/queue",
  conversations: "/dashboard/conversations",
  "queue-status": "/dashboard/queue-status",
  "dlq-inspector": "/dashboard/dlq",
  fraud: "/dashboard/fraud",
  trace: "/dashboard/traces",
  supervisor: "/dashboard/supervisor",
  approvals: "/dashboard/approvals",
  cognition: "/dashboard/cognition",
  knowledge: "/dashboard/knowledge",
  governance: "/dashboard/governance",
  crisis: "/dashboard/crisis",
  topology: "/dashboard/topology",
  channels: "/dashboard/channels",
  connectors: "/dashboard/connectors",
  "action-policy": "/dashboard/action-policy",
  "config-approvals": "/dashboard/config-approvals",
  onboarding: "/dashboard/onboarding",
  team: "/dashboard/team",
  audit: "/dashboard/audit",
  settings: "/dashboard/settings",
} as const;

export type DashboardViewId = keyof typeof dashboardRoutes;
