[pytest]
testpaths = tests
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
norecursedirs = _deprecated venv .git .pytest_cache __pycache__
filterwarnings =
    ignore::DeprecationWarning
addopts = -ra --strict-markers
