[pytest]
testpaths = tests
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
norecursedirs = _deprecated venv .git .pytest_cache __pycache__
filterwarnings =
    error::DeprecationWarning
    ignore::DeprecationWarning
addopts = -ra --strict-markers
markers =
    smoke: mark end-to-end smoke test
    requires_postgres: mark test as requiring a PostgreSQL database
    integration: mark test as integration test
    unit: mark test as unit test
    slow: mark test as slow test
