"""Provider-backed SME reviewer built on grounded generation.

The SME reviewer is NOT a parallel LLM path: it reuses the same governed
``GroundedConversationGenerationRuntime`` the resolution runtime uses, so an
SME recommendation is produced by the real provider (Anthropic when
configured) and carries grounding segments. Operator guidance is threaded in
as untrusted conversation context; it can steer wording/questions but the
generator is constrained to grounded facts and the approval path re-runs the
full resolution governance gate before anything is delivered.
"""

from __future__ import annotations

from datetime import datetime, timezone

from app.boundary.translation import CANONICAL_LANGUAGE
from app.runtime.conversation_generation import (
    ConversationGenerationRequest,
    ConversationGenerationRuntimeProtocol,
    render_grounded_reply,
)
from app.sme.models import SmeCaseContext, SmeRecommendation


class GeneratedSmeReviewer:
    """SME reviewer that recommends via governed grounded generation."""

    def __init__(
        self,
        *,
        generation_runtime: ConversationGenerationRuntimeProtocol,
    ) -> None:
        self._generation = generation_runtime

    async def review(
        self,
        context: SmeCaseContext,
        *,
        recommendation_id: str,
        guidance: str | None = None,
    ) -> SmeRecommendation:
        evidence = tuple(dict(item) for item in context.citations)
        confidence = _confidence(context)
        history = [dict(turn) for turn in context.timeline]
        if guidance is not None and guidance.strip():
            # Guidance arrives already wrapped in untrusted delimiters by the
            # SmeReviewRuntime; it steers but cannot grant ungrounded promises.
            history.append(
                {"role": "operator_guidance", "content": guidance}
            )
        result = await self._generation.generate_reply(
            ConversationGenerationRequest(
                tenant_id=context.tenant_id,
                session_id=context.session_id or "",
                diagnostic_summary=(
                    context.issue_summary or context.entry_category
                ),
                diagnostic_category=context.entry_category,
                diagnostic_confidence=confidence,
                original_content=context.issue_summary or "",
                source_language=str(
                    context.metadata.get("source_language") or CANONICAL_LANGUAGE
                ),
                evidence=evidence,
                conversation_history=tuple(history),
                target_language=CANONICAL_LANGUAGE,
            )
        )
        reply_segments = tuple(
            segment.to_dict() for segment in result.draft.segments
        )
        risk_flags: list[str] = []
        if not evidence:
            risk_flags.append("citation_review_required")
        if guidance is not None and guidance.strip():
            risk_flags.append("operator_guided")
        return SmeRecommendation(
            recommendation_id=recommendation_id,
            recommended_reply=render_grounded_reply(result.draft),
            recommended_actions=tuple(
                dict(action) for action in context.recommended_actions
            ),
            rationale=(
                "SME recommendation generated by governed grounded generation "
                f"({result.provider}:{result.model})."
            ),
            confidence=confidence,
            citations=evidence,
            risk_flags=tuple(dict.fromkeys(risk_flags)),
            created_at=datetime.now(timezone.utc),
            reply_segments=reply_segments,
            metadata={
                "reviewer": f"{result.provider}:{result.model}",
                "proposal_only": True,
                "entry_category": context.entry_category,
                "generation_provider": result.provider,
                "generation_model": result.model,
                "guidance_incorporated": bool(
                    guidance is not None and guidance.strip()
                ),
            },
        )


def _confidence(context: SmeCaseContext) -> float:
    raw = context.metadata.get("confidence")
    if isinstance(raw, bool):
        return 0.5
    if isinstance(raw, int | float):
        return max(0.0, min(1.0, float(raw)))
    return 0.0


__all__ = ["GeneratedSmeReviewer"]
